// <auto-generated />
using BugCatUsuario.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugCatUsuario.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231020173433_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BugCatUsuario.Models.Tarjeta", b =>
                {
                    b.Property<int>("TarjetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarjetaId"), 1L, 1);

                    b.Property<int>("ccv")
                        .HasColumnType("int");

                    b.Property<string>("fechaCad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("nroTarjeta")
                        .HasColumnType("bigint");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("TarjetaId");

                    b.HasIndex("usuarioId");

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("BugCatUsuario.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BugCatUsuario.Models.Tarjeta", b =>
                {
                    b.HasOne("BugCatUsuario.Models.Usuario", "usuario")
                        .WithMany("tarjeta")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("BugCatUsuario.Models.Usuario", b =>
                {
                    b.Navigation("tarjeta");
                });
#pragma warning restore 612, 618
        }
    }
}
